#sql_statement.py

CREATE_USER_TYPE_TABLE  = """
CREATE TABLE IF NOT EXISTS UserType (
  user_type_id INT AUTO_INCREMENT PRIMARY KEY,
  user_type VARCHAR(45) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
"""


CREATE_DB = "CREATE DATABASE IF NOT EXISTS"
DEFAULT_OB_NAME = "memopark_db"

