"""Add peek_penalty and assist_penalty columns to Score

Revision ID: 59f2eb8f38b6
Revises: c5b8b437831d
Create Date: 2025-10-30 19:59:32.817319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f2eb8f38b6'
down_revision = 'c5b8b437831d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peek_penalty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assist_penalty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Score', schema=None) as batch_op:
        batch_op.drop_column('assist_penalty')
        batch_op.drop_column('peek_penalty')

    # ### end Alembic commands ###
