"""Add finalScreenTime and finalMapViewCount to ParkingEvent

Revision ID: c5b8b437831d
Revises: de27b9d9c905
Create Date: 2025-10-22 03:00:22.148103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b8b437831d'
down_revision = 'de27b9d9c905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ParkingEvent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalScreenTime', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('finalMapViewCount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ParkingEvent', schema=None) as batch_op:
        batch_op.drop_column('finalMapViewCount')
        batch_op.drop_column('finalScreenTime')

    # ### end Alembic commands ###
