"""Add navigation_started_at to ParkingEvent

Revision ID: d31c031b5d67
Revises: c3f8d6182bd2
Create Date: 2025-10-20 18:52:37.796809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31c031b5d67'
down_revision = 'c3f8d6182bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ParkingEvent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('navigation_started_at', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ParkingEvent', schema=None) as batch_op:
        batch_op.drop_column('navigation_started_at')

    # ### end Alembic commands ###
