"""Add estimated_time to ParkingEvent

Revision ID: de27b9d9c905
Revises: 9bceeb0863b2
Create Date: 2025-10-21 11:34:45.465556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de27b9d9c905'
down_revision = '9bceeb0863b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ParkingEvent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'retrieving', 'retrieved', 'score_watched', 'expired'),
               type_=sa.Enum('active', 'retrieved', 'expired', 'retrieving', 'score_watched', name='statusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ParkingEvent', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('active', 'retrieved', 'expired', 'retrieving', 'score_watched', name='statusenum'),
               type_=mysql.ENUM('active', 'retrieving', 'retrieved', 'score_watched', 'expired'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.drop_column('estimated_time')

    # ### end Alembic commands ###
